# Promise 

- [ ] `Промисы (Promises)` - это объекты, представляющие асинхронные операции. Они используются для обработки асинхронных действий, таких как запросы к серверу, чтение файлов или выполнение долгих вычислений, где результат неизвестен сразу.

- [ ] Промисы имеют три состояния: `ожидание (pending)`, `выполнено (fulfilled)` и `отклонено (rejected)`.

- [ ] Промисы обеспечивают `цепочки обработки (chaining)`, которые позволяют последовательно выполнять операции после завершения асинхронных действий.

```javascript
  let promise = new Promise(function(resolve, reject) {
    // функция-исполнитель (executor)
  });
```

<br>

  - [x] Функция, переданная в конструкцию `new Promise` - это `исполнитель (executor)`. Она должна содержать «создающий» код, который когда-нибудь создаст результат.
  - [x] Когда он получает результат, сейчас или позже – не важно, он должен вызвать один из этих колбэков:

    + `resolve(value)` — если работа завершилась успешно, с результатом `value`.
    + `reject(error)` — если произошла ошибка, `error` – объект ошибки. 

  <br>

  - [x] У объекта `promise`, возвращаемого конструктором `new Promise`, есть внутренние свойства:

    + `state` — вначале `"pending" («ожидание»)`, потом меняется на `"fulfilled" («выполнено успешно»)` при вызове `resolve` или на `"rejected" («выполнено с ошибкой»)` при вызове `reject`.
    + `result` — вначале `undefined`, далее изменяется на `value` при вызове `resolve(value)` или на `error` при вызове `reject(error)`.
       
    ![image](https://github.com/acidshotgun/learn-js-vanilla/assets/117285472/b180dfdf-c4b3-4ea9-8689-50bfa96e4226)

  <br>

  - [x] Пример, при котором возвращается переданное сообщение либо ошибка. Асинхронный код, ожидаем результат через опр. время.

  ```javascript
    const showMessage = (message) => {
      /*
        Ф-я возвращает промис
        Внутри исполнитель (executor)
        В зависимости от условия вызывает resolve|reject
      */
      return new Promise((resolve, reject) => {
        if (message.length < 10) {
          setTimeout(() => {
            reject(new Error("Ошибка! Короткое сообщение!"));
          }, 500);
        } else {
          setTimeout(() => {
            resolve(message);
          }, 2000);
        }
      });
    };
    
    /*
      Вызов showMessage() вернет промис, который нужно обработать
      Используется then|catch (finally - опционально)
    */
    showMessage("Привет! Теперь это длинное сообщение")
      .then((res) => console.log(res))
      .catch((error) => console.log(error))
      .finally(() => console.log("Промис завершен."));
  ```



